### ISSUE TITLE
enhancement : Add the "integra watermeter" font

### ISSUE THREAD

**Issue by nliaudat** [haverland/Tenth-of-step-of-a-meter-digit#6]
Hi, 
[Integra water meter](https://integra-metering.com/) use "bahnschrift light condensed" font and actually the "6" & "4" are not recognized. 

Can you add the "bahnschrift light condensed" and the "Din 1451" to your digit processing ? 
They are bot free and allowed for commercial use

You can download them [here](https://www.dropbox.com/sh/2kt206bhwbgzjjx/AACpZ2tP3N2gIa_JSdeCgNHna?dl=0) 

Regards

**Comment by haverland** [comment]
We are not really able to add fonts to a model. I tried it with no real good results. The better way would be to give us examples of the digits.

You can use https://github.com/haverland/collectmeterdigits to easy collect you digits and for labeling.

**Comment by nliaudat** [comment]
Ok, 
It is not possible to generate custom font images from https://www.kaggle.com/code/frankhaverland/electric-meter-dataset-from-fonts ?

The errors are mainly with red digits. 

I'll try to generate images. 

Regards

**Comment by haverland** [comment]
Was my first intention to get a mostly full collection of images. But on real meters I've got only a accuracy of 60%. Not real very good. So I now completely removed the generated images and I'm using collected images with quite good results.

If you want, I could integrate them if the results on your devices are better.

**Comment by nliaudat** [comment]
I'll collect images in the next 10 days and try to make good predictions with [collectmeterdigits](https://github.com/haverland/collectmeterdigits). That's no so easy to set 3.5 or 3.6 :)

**Comment by haverland** [comment]
If you have .0 of all digits i could help to create the others

**Comment by haverland** [comment]
It do you mean, you dont know what kind of number it is? 
i relabel all incomming Images, of it is not correct labeled.

**Comment by haverland** [comment]
Now I know why it is not easy to label for you. Two suggestions:
1.) Play with your focus of the camera. Sharpe images have a better recognition.
2.) You should setup your ROIs like 

![](https://github.com/haverland/collectmeterdigits/raw/main/images/ROI-setup.png)

and do not lock the aspect ratio on setup.

**Comment by haverland** [comment]
Could you upload a picture of you meter?

**Comment by haverland** [comment]
You can try https://github.com/haverland/Tenth-of-step-of-a-meter-digit/blob/dev/output/dig-class100-s2_20220905-193211_q.tflite

**Comment by nliaudat** [comment]
![alg_roi](https://user-images.githubusercontent.com/6782613/188502555-f399d77d-61af-4e0a-97cc-161e8ab365e6.jpg)

and 

![alg_roi_2](https://user-images.githubusercontent.com/6782613/188502573-914d68b1-c9d6-4de8-bded-ea1018d76b6d.jpg)

**Comment by haverland** [comment]
Thanks. Reduce the height of the ROIs. The wide is ok. At the last digit I would use the same height as the digit left.

**Comment by nliaudat** [comment]
Ok, I'll try. Many thanks

**Comment by haverland** [comment]
I've tested with font, but in comparing without font the results are better.

**Comment by nliaudat** [comment]
![alg_roi](https://user-images.githubusercontent.com/6782613/189368999-7173a700-0fe0-435f-b34d-b4aff01816ac.jpg)


I've reduced ROI and aligned the ROI horizontally. Now everything works well. 
Many many thanks !
